# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
   name: postgres-db-lbb
spec:
   selector:
     app: postgresql-db
   type: LoadBalancer
   ports:
   - port: 5432
     targetPort: 5432